---
  version: "2"
  services:
    web:
      container_name: web-app
      build: "."
      image: web-app:latest
      env_file: .env
      volumes:
        - .:/usr/src/app
        - node_modules:/usr/src/app/node_modules
        - public:/usr/src/app/public
      ports:
        - 3000:3000
        - 3001:3001
      command: npm run dev
  volumes:
    node_modules:
    public: