---
  version: "2"
  services:
    web:
      container_name: web-app
      build: "."
      image: web-app:latest
      env_file: .env
      volumes:
        - .:/usr/src/app
      ports:
        - 3000:3000